site_name: Desarrollo Web
site_url: https://atorrescode.github.io/dw/
# docs_dir: md
# site_dir: docs
theme:
   name: 'material'
   features:
    - navigation.sections
    - navigation.top
    - content.code.copy
   font:
    text: 'Roboto, sans-serif'
    code: 'Courier New, monospace'
   icon:
    repo: 'fontawesome/brands/github'
   palette:
    - scheme: default
      toggle:
          icon: material/brightness-7 
          name: Canvia a mode oscur

    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Canvia a mode clar
   logo: assets/img/pato_pixelart_icono.ico
   favicon: assets/img/pato_pixelart_icono.ico

nav:
    - Home: index.md
    - Unidad 1. Introducción al desarrollo web:
      - 1. Arquitecturas web: u01-introduccion-desarrollo-web/r01-arquitecturas-web.md
      - Actividades: u01-introduccion-desarrollo-web/a01.md
    - Unidad 2. JavaScript: u02-javascript/index.md
extra_css:
  - assets/css/style.css
extra_templates:
plugins:
  - search
  # - with-pdf
  # - pdf-export:
  #     combined: true
  # - page-to-pdf
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.embed